### model
model_name_or_path: /mnt/mcu/public/plms/qwen1.5_7/qwen/Qwen1___5-7B/

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: step4_zym
template: qwen
cutoff_len: 3000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/mcu/chongyangwang/PLM/sft
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
